# From Data to Business Decision

In [218]:
# Importing libraries
import pandas as pd
import numpy as np

In [219]:
# Loading excel file as a dataframe
df = pd.read_excel("Book.xlsx")
#print(df.columns)
#print(df[["Customer_ID "]])
df

,Customer_ID,Age,Gender,City,Income,Visits,Avg_Spend,Purchased,Signup_Date
0,C001,25,Female,Toronto,52000,5,45.5,Yes,2025-01-10
1,C002,34,Male,Toronto,68000,8,72.3,No,2025-01-15
2,C003,29,F,Brampton,55000,6,61.2,Yes,2025/01/20
3,C004,42,Male,Mississauga,82000,12,95.0,Yes,2025-02-01
4,C005,31,Female,Toronto,NaN,4,38.5,No,2025-02-05
5,C006,31,Female,Toronto,61000,7,55.75,Yes,2025-02-08
6,C007,150,Male,Brampton,59000,5,49.0,No,2025-02-10
7,C008,27,M,Toronto,47000,3,35.25,No,2025-02-12
8,C009,36,Male,Toronto,71000,10,88.4,Yes,2025-02-15
9,C010,29,Female,Brampton,54000,6,NaN,Yes,2025-02-18
10,C011,34,Male,Toronto,68000,8,72.3,No,2025-01-15
11,C012,24,Female,Toronto,45000,2,29.99,No,2025-02-20
12,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Remove completely empty rows
# Replacing extra whitespaces '\xa0' for empty string Ex: 'Customer_ID\xa0' -> 'Customer_ID '
df = df.map(
    lambda x: x.replace("\xa0", " ").strip()
    if isinstance(x, str)
    else x
)

# Convert empty strings to NaN
df = df.replace(r"^\s*$", np.nan, regex=True)

# Remove rows where every column is missing
# The reset_index(drop=True) is useful because after removing row 12, pandas may otherwise preserve the original index.
df = df.dropna(how='all').reset_index(drop=True)

df

,Customer_ID,Age,Gender,City,Income,Visits,Avg_Spend,Purchased,Signup_Date
0,C001,25,Female,Toronto,52000,5,45.5,Yes,2025-01-10
1,C002,34,Male,Toronto,68000,8,72.3,No,2025-01-15
2,C003,29,F,Brampton,55000,6,61.2,Yes,2025/01/20
3,C004,42,Male,Mississauga,82000,12,95.0,Yes,2025-02-01
4,C005,31,Female,Toronto,NaN,4,38.5,No,2025-02-05
5,C006,31,Female,Toronto,61000,7,55.75,Yes,2025-02-08
6,C007,150,Male,Brampton,59000,5,49.0,No,2025-02-10
7,C008,27,M,Toronto,47000,3,35.25,No,2025-02-12
8,C009,36,Male,Toronto,71000,10,88.4,Yes,2025-02-15
9,C010,29,Female,Brampton,54000,6,NaN,Yes,2025-02-18
10,C011,34,Male,Toronto,68000,8,72.3,No,2025-01-15
11,C012,24,Female,Toronto,45000,2,29.99,No,2025-02-20

## Part 1 — Accessing & Filtering Data

### Q1 - How many rows and columns are in the dataset?

In [221]:
df.shape

(12, 9)

### Q2 - Which columns are available, and what data type does each contain?

In [235]:
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'City', 'Income', 'Visits', 'Avg_Spend',
       'Purchased', 'Signup_Date'],
      dtype='str')

In [223]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer_ID  12 non-null     str
 1   Age          12 non-null     str
 2   Gender       12 non-null     str
 3   City         12 non-null     str
 4   Income       12 non-null     str
 5   Visits       12 non-null     str
 6   Avg_Spend    12 non-null     str
 7   Purchased    12 non-null     str
 8   Signup_Date  12 non-null     str
dtypes: str(9)
memory usage: 996.0 bytes

In [224]:
# Converting columns types
# Text / categorical columns
df["Customer_ID"] = df["Customer_ID"].astype("string")
df["Gender"] = df["Gender"].astype("string")
df["City"] = df["City"].astype("string")

# Numeric columns
df["Age"] = pd.to_numeric(df["Age"], errors="coerce").astype("Int64")
df["Income"] = pd.to_numeric(df["Income"], errors="coerce")
df["Visits"] = pd.to_numeric(df["Visits"], errors="coerce").astype("Int64")
df["Avg_Spend"] = pd.to_numeric(df["Avg_Spend"], errors="coerce")

# Date
df["Signup_Date"] = pd.to_datetime(df["Signup_Date"], errors="coerce")

df.dtypes

Customer_ID            string
Age                     Int64
Gender                 string
City                   string
Income                float64
Visits                  Int64
Avg_Spend             float64
Purchased                 str
Signup_Date    datetime64[us]
dtype: object

### Q3 - Display only Customer_ID, Age, City, and Purchased.

In [225]:
df[['Customer_ID','Age','City','Purchased']]

   Customer_ID  Age         City Purchased
0         C001   25      Toronto       Yes
1         C002   34      Toronto        No
2         C003   29     Brampton       Yes
3         C004   42  Mississauga       Yes
4         C005   31      Toronto        No
5         C006   31      Toronto       Yes
6         C007  150     Brampton        No
7         C008   27      Toronto        No
8         C009   36      Toronto       Yes
9         C010   29     Brampton       Yes
10        C011   34      Toronto        No
11        C012   24      Toronto        No

### Q4 - Which customers are from Toronto?

In [226]:
# filtering customers in Toronto
df[df["City"]=="Toronto"]

,Customer_ID,Age,Gender,City,Income,Visits,Avg_Spend,Purchased,Signup_Date
0,C001,25,Female,Toronto,52000.0,5,45.50,Yes,2025-01-10
1,C002,34,Male,Toronto,68000.0,8,72.30,No,2025-01-15
4,C005,31,Female,Toronto,NaN,4,38.50,No,2025-02-05
5,C006,31,Female,Toronto,61000.0,7,55.75,Yes,2025-02-08
7,C008,27,M,Toronto,47000.0,3,35.25,No,2025-02-12
8,C009,36,Male,Toronto,71000.0,10,88.40,Yes,2025-02-15
10,C011,34,Male,Toronto,68000.0,8,72.30,No,2025-01-15
11,C012,24,Female,Toronto,45000.0,2,29.99,No,2025-02-20

### Q5 - Which customers visited more than 6 times?

In [227]:
df.loc[df["Visits"]>6 , ["Customer_ID"]]

   Customer_ID
1         C002
3         C004
5         C006
8         C009
10        C011

### Q6 - Which customers are from Toronto and purchased?

In [228]:
df.loc[(df["City"]=="Toronto") & (df["Purchased"]=="Yes"), ["Customer_ID"]]

  Customer_ID
0        C001
5        C006
8        C009

### Q7 - Which customers have income above 60,000 or more than 8 visits?

In [229]:
df.loc[(df["Income"]>60000) | (df["Visits"]>8), ["Customer_ID"]]

   Customer_ID
1         C002
3         C004
5         C006
8         C009
10        C011

## Part 2 — Data Wrangling

### Q1 - Which columns contain missing values, and how many are missing in each?

In [230]:
# Coung missing values per column
print(df.isnull().sum())

# Check if any missing values exist
# df.isnull().any()

# Total missing values
print("Total number of missing values" ,df.isnull().sum().sum())

Customer_ID    0
Age            0
Gender         0
City           0
Income         1
Visits         0
Avg_Spend      1
Purchased      0
Signup_Date    1
dtype: int64
Total number of missing values 3

### Q2 - How would you handle the missing Income value? Explain your choice.

In [231]:
# Replacing missing income value for the average
# I would replace the missing Income with the median income rather than dropping the row. 
# Since only one value is missing and the dataset is small, imputation preserves the customer record. 
# The median is preferable because income can contain outliers that could distort the mean.
df["Income"] = df["Income"].fillna(df["Income"].median())
df

,Customer_ID,Age,Gender,City,Income,Visits,Avg_Spend,Purchased,Signup_Date
0,C001,25,Female,Toronto,52000.0,5,45.50,Yes,2025-01-10
1,C002,34,Male,Toronto,68000.0,8,72.30,No,2025-01-15
2,C003,29,F,Brampton,55000.0,6,61.20,Yes,NaT
3,C004,42,Male,Mississauga,82000.0,12,95.00,Yes,2025-02-01
4,C005,31,Female,Toronto,59000.0,4,38.50,No,2025-02-05
5,C006,31,Female,Toronto,61000.0,7,55.75,Yes,2025-02-08
6,C007,150,Male,Brampton,59000.0,5,49.00,No,2025-02-10
7,C008,27,M,Toronto,47000.0,3,35.25,No,2025-02-12
8,C009,36,Male,Toronto,71000.0,10,88.40,Yes,2025-02-15
9,C010,29,Female,Brampton,54000.0,6,NaN,Yes,2025-02-18
10,C011,34,Male,Toronto,68000.0,8,72.30,No,2025-01-15
11,C012,24,Female,Toronto,45000.0,2,29.99,No,2025-02-20

### Q3 - How would you standardize the Gender values so that F, female, and Female are consistent?

In [232]:
standardize = {"female": "F", "f": "F", "male": "M", "m": "M"}

df["Gender"] = df["Gender"].str.strip().str.lower()
df["Gender"] = df["Gender"].replace(standardize)

df

,Customer_ID,Age,Gender,City,Income,Visits,Avg_Spend,Purchased,Signup_Date
0,C001,25,F,Toronto,52000.0,5,45.50,Yes,2025-01-10
1,C002,34,M,Toronto,68000.0,8,72.30,No,2025-01-15
2,C003,29,F,Brampton,55000.0,6,61.20,Yes,NaT
3,C004,42,M,Mississauga,82000.0,12,95.00,Yes,2025-02-01
4,C005,31,F,Toronto,59000.0,4,38.50,No,2025-02-05
5,C006,31,F,Toronto,61000.0,7,55.75,Yes,2025-02-08
6,C007,150,M,Brampton,59000.0,5,49.00,No,2025-02-10
7,C008,27,M,Toronto,47000.0,3,35.25,No,2025-02-12
8,C009,36,M,Toronto,71000.0,10,88.40,Yes,2025-02-15
9,C010,29,F,Brampton,54000.0,6,NaN,Yes,2025-02-18
10,C011,34,M,Toronto,68000.0,8,72.30,No,2025-01-15
11,C012,24,F,Toronto,45000.0,2,29.99,No,2025-02-20

### Q4 - Are there duplicate customer records? Identify and handle them appropriately.

In [233]:
# Checking for entire duplicated rows
print(f"Duplicated rows : {df.duplicated().sum()}")

# For our data, C002 and C011 would not be considered duplicates because their Customer_ID values differ.
# Check duplicates excluding Customer_ID
print(f"Duplicated excluding Customer_ID : {df.duplicated(subset=df.columns.difference(["Customer_ID"])).sum()}")

# Investigating before deleting
print(df[df["Customer_ID"].isin(["C002", "C011"])])

# Droping the duplicated records keeping first occurrence
df = df.drop_duplicates(
    subset=df.columns.difference(["Customer_ID"]),
    keep="first"
).reset_index(drop=True)
df

Duplicated rows : 0
Duplicated excluding Customer_ID : 1
   Customer_ID  Age Gender     City   Income  Visits  Avg_Spend Purchased  \
1         C002   34      M  Toronto  68000.0       8       72.3        No
10        C011   34      M  Toronto  68000.0       8       72.3        No

   Signup_Date
1   2025-01-15
10  2025-01-15

,Customer_ID,Age,Gender,City,Income,Visits,Avg_Spend,Purchased,Signup_Date
0,C001,25,F,Toronto,52000.0,5,45.50,Yes,2025-01-10
1,C002,34,M,Toronto,68000.0,8,72.30,No,2025-01-15
2,C003,29,F,Brampton,55000.0,6,61.20,Yes,NaT
3,C004,42,M,Mississauga,82000.0,12,95.00,Yes,2025-02-01
4,C005,31,F,Toronto,59000.0,4,38.50,No,2025-02-05
5,C006,31,F,Toronto,61000.0,7,55.75,Yes,2025-02-08
6,C007,150,M,Brampton,59000.0,5,49.00,No,2025-02-10
7,C008,27,M,Toronto,47000.0,3,35.25,No,2025-02-12
8,C009,36,M,Toronto,71000.0,10,88.40,Yes,2025-02-15
9,C010,29,F,Brampton,54000.0,6,NaN,Yes,2025-02-18
10,C012,24,F,Toronto,45000.0,2,29.99,No,2025-02-20