In [16]:
# Importing required libraries
import pandas as pd

In [17]:
# Read the csv file into a pandas dataframe
df = pd.read_csv('survey_data_updated.csv')

# Display the first few rows of the data
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
1,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
2,10,I am a developer by profession,35-44 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Bootstrapping a business,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
3,11,"I used to be a developer by profession, but no...",35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Books;Written Tutorial...,...,25.0,10.0,0.0,15.0,0.0,0.0,Appropriate in length,Easy,NaN,8.0
4,12,I am a developer by profession,45-54 years old,"Employed, full-time",In-person,Apples,Hobby;School or academic work,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Books / Physical media;School (i.e., Universit...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN

In [18]:
# Check the columns
df.describe()

# Cleaning spaces from column names
df.columns = (
    df.columns
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

In [19]:
summary = pd.DataFrame({
    'Data Type': df.dtypes,
    'Unique Values': df.nunique(dropna=False),
    'Missing Values': df.isna().sum()
})

summary

                               Data Type  Unique Values  Missing Values
ResponseId                         int64          18845               0
MainBranch                           str              5               0
Age                                  str              8               0
Employment                           str             60               0
RemoteWork                           str              4               6
Check                                str              1               0
CodingActivities                     str            107               0
EdLevel                              str              8               0
LearnCode                            str            359              37
LearnCodeOnline                      str           5741            2914
TechDoc                              str             99            4971
YearsCode                            str             53              51
YearsCodePro                         str             53             776
DevType                              str             35              44
OrgSize                              str             11             875
PurchaseInfluence                    str              4             888
BuyNewTool                           str            194            1339
BuildvsBuy                           str              4            1794
TechEndorse                          str            349            1513
Country                              str            161               0
Currency                             str            126             820
CompTotal                        float64           1832            5376
LanguageHaveWorkedWith               str           9343               0
LanguageWantToWorkWith               str           9778               0
LanguageAdmired                      str           6191               0
DatabaseHaveWorkedWith               str           5635               0
DatabaseWantToWorkWith               str           5453               0
DatabaseAdmired                      str           3142               0
PlatformHaveWorkedWith               str           3809               0
PlatformWantToWorkWith               str           3398               0
PlatformAdmired                      str           2091               0
WebframeHaveWorkedWith               str           7702               0
WebframeWantToWorkWith               str           7277               0
WebframeAdmired                      str           4217               0
EmbeddedHaveWorkedWith               str            693           11943
EmbeddedWantToWorkWith               str            626           12932
EmbeddedAdmired                      str            496           13064
MiscTechHaveWorkedWith               str           4662            4787
MiscTechWantToWorkWith               str           5274            5776
MiscTechAdmired                      str           2911            6458
ToolsTechHaveWorkedWith              str           9993             639
ToolsTechWantToWorkWith              str           9400             911
ToolsTechAdmired                     str           7366            1047
NEWCollabToolsHaveWorkedWith         str           6414             146
NEWCollabToolsWantToWorkWith         str           5004             299
NEWCollabToolsAdmired                str           4132             366
OpSysPersonal use                    str           1421             144
OpSysProfessional use                str           1197             221
OfficeStackAsyncHaveWorkedWith       str           3878            1626
OfficeStackAsyncWantToWorkWith       str           2608            2840
OfficeStackAsyncAdmired              str           1964            3192
OfficeStackSyncHaveWorkedWith        str           2742             385
OfficeStackSyncWantToWorkWith        str           1941            1186
OfficeStackSyncAdmired               str           1638            1574
AISearchDevHaveWorkedWith            str           1461            2977
AISearchDevWantToWorkWith            str           1360            4132
AISearchDevAdmired                   str            928            4299
NEWSOSites                           str             33              72
SOVisitFreq                          str              6             170
SOAccount                            str              4             163
SOPartFreq                           str              7            3539
SOHow                                str             99             267
SOComm                               str              7             195
AISelect                             str              4              58
AISent                               str              7            3449
AIBen                                str             99            6007
AIAcc                                str              6            5874
AIComplex                            str              6            5921
AIToolCurrently Using                str            888            6314
AIToolInterested in Using            str           1456            7656
AIToolNot interested in Using        str            998           10067
AINextMuch more integrated           str            504           13676
AINextNo change                      str            362           14468
AINextMore integrated                str            605            9816
AINextLess integrated                str            139           18093
AINextMuch less integrated           str            131           18492
AIThreat                             str              4            3476
AIEthics                             str            123            4279
AIChallenges                         str            211            5137
TBranch                              str              3            1717
ICorPM                               str              3            6533
WorkExp                          float64             51            6571
Knowledge_1                          str              6            6926
Knowledge_2                          str              6            7163
Knowledge_3                          str              6            7136
Knowledge_4                          str              6            7152
Knowledge_5                          str              6            7205
Knowledge_6                          str              6            7208
Knowledge_7                          str              6            7250
Knowledge_8                          str              6            7261
Knowledge_9                          str              6            7289
Frequency_1                          str              6            7023
Frequency_2                          str              6            7028
Frequency_3                          str              6            7262
TimeSearching                        str              6            6827
TimeAnswering                        str              6            6855
Frustration                          str            821            7054
ProfessionalTech                     str            472            7169
ProfessionalCloud                    str              4            6856
ProfessionalQuestion                 str             10            6842
Industry                             str             16            6819
JobSatPoints_1                   float64             82            6708
JobSatPoints_4                   float64             60            6682
JobSatPoints_5                   float64             65            6675
JobSatPoints_6                   float64             75            6660
JobSatPoints_7                   float64             74            6660
JobSatPoints_8                   float64             78            6654
JobSatPoints_9                   float64             74            6661
JobSatPoints_10                  float64             64            6658
JobSatPoints_11                  float64             67            6663
SurveyLength                         str              4             520
SurveyEase                           str              4             509
ConvertedCompYearly              float64           3366            9295
JobSat                           float64             12            6734

In [20]:
pd.set_option('display.max_rows', None)

summary

                               Data Type  Unique Values  Missing Values
ResponseId                         int64          18845               0
MainBranch                           str              5               0
Age                                  str              8               0
Employment                           str             60               0
RemoteWork                           str              4               6
Check                                str              1               0
CodingActivities                     str            107               0
EdLevel                              str              8               0
LearnCode                            str            359              37
LearnCodeOnline                      str           5741            2914
TechDoc                              str             99            4971
YearsCode                            str             53              51
YearsCodePro                         str             53             776
DevType                              str             35              44
OrgSize                              str             11             875
PurchaseInfluence                    str              4             888
BuyNewTool                           str            194            1339
BuildvsBuy                           str              4            1794
TechEndorse                          str            349            1513
Country                              str            161               0
Currency                             str            126             820
CompTotal                        float64           1832            5376
LanguageHaveWorkedWith               str           9343               0
LanguageWantToWorkWith               str           9778               0
LanguageAdmired                      str           6191               0
DatabaseHaveWorkedWith               str           5635               0
DatabaseWantToWorkWith               str           5453               0
DatabaseAdmired                      str           3142               0
PlatformHaveWorkedWith               str           3809               0
PlatformWantToWorkWith               str           3398               0
PlatformAdmired                      str           2091               0
WebframeHaveWorkedWith               str           7702               0
WebframeWantToWorkWith               str           7277               0
WebframeAdmired                      str           4217               0
EmbeddedHaveWorkedWith               str            693           11943
EmbeddedWantToWorkWith               str            626           12932
EmbeddedAdmired                      str            496           13064
MiscTechHaveWorkedWith               str           4662            4787
MiscTechWantToWorkWith               str           5274            5776
MiscTechAdmired                      str           2911            6458
ToolsTechHaveWorkedWith              str           9993             639
ToolsTechWantToWorkWith              str           9400             911
ToolsTechAdmired                     str           7366            1047
NEWCollabToolsHaveWorkedWith         str           6414             146
NEWCollabToolsWantToWorkWith         str           5004             299
NEWCollabToolsAdmired                str           4132             366
OpSysPersonal use                    str           1421             144
OpSysProfessional use                str           1197             221
OfficeStackAsyncHaveWorkedWith       str           3878            1626
OfficeStackAsyncWantToWorkWith       str           2608            2840
OfficeStackAsyncAdmired              str           1964            3192
OfficeStackSyncHaveWorkedWith        str           2742             385
OfficeStackSyncWantToWorkWith        str           1941            1186
OfficeStackSyncAdmired               str           1638            1574
AISearchDevHaveWorkedWith            str           1461            2977
AISearchDevWantToWorkWith            str           1360            4132
AISearchDevAdmired                   str            928            4299
NEWSOSites                           str             33              72
SOVisitFreq                          str              6             170
SOAccount                            str              4             163
SOPartFreq                           str              7            3539
SOHow                                str             99             267
SOComm                               str              7             195
AISelect                             str              4              58
AISent                               str              7            3449
AIBen                                str             99            6007
AIAcc                                str              6            5874
AIComplex                            str              6            5921
AIToolCurrently Using                str            888            6314
AIToolInterested in Using            str           1456            7656
AIToolNot interested in Using        str            998           10067
AINextMuch more integrated           str            504           13676
AINextNo change                      str            362           14468
AINextMore integrated                str            605            9816
AINextLess integrated                str            139           18093
AINextMuch less integrated           str            131           18492
AIThreat                             str              4            3476
AIEthics                             str            123            4279
AIChallenges                         str            211            5137
TBranch                              str              3            1717
ICorPM                               str              3            6533
WorkExp                          float64             51            6571
Knowledge_1                          str              6            6926
Knowledge_2                          str              6            7163
Knowledge_3                          str              6            7136
Knowledge_4                          str              6            7152
Knowledge_5                          str              6            7205
Knowledge_6                          str              6            7208
Knowledge_7                          str              6            7250
Knowledge_8                          str              6            7261
Knowledge_9                          str              6            7289
Frequency_1                          str              6            7023
Frequency_2                          str              6            7028
Frequency_3                          str              6            7262
TimeSearching                        str              6            6827
TimeAnswering                        str              6            6855
Frustration                          str            821            7054
ProfessionalTech                     str            472            7169
ProfessionalCloud                    str              4            6856
ProfessionalQuestion                 str             10            6842
Industry                             str             16            6819
JobSatPoints_1                   float64             82            6708
JobSatPoints_4                   float64             60            6682
JobSatPoints_5                   float64             65            6675
JobSatPoints_6                   float64             75            6660
JobSatPoints_7                   float64             74            6660
JobSatPoints_8                   float64             78            6654
JobSatPoints_9                   float64             74            6661
JobSatPoints_10                  float64             64            6658
JobSatPoints_11                  float64             67            6663
SurveyLength                         str              4             520
SurveyEase                           str              4             509
ConvertedCompYearly              float64           3366            9295
JobSat                           float64             12            6734

In [22]:
# Let's split the LanguageWantToWorkWith, LanguagesHaveWorkedWith per value counts
language_want_work_counts = (
    df["LanguageWantToWorkWith"]
    .dropna()
    .str.split(";")
    .explode()
    .value_counts()
)

language_have_worked_counts = (
    df["LanguageHaveWorkedWith"]
    .dropna()
    .str.split(";")
    .explode()
    .value_counts()
)

databases_have_worked_counts = (
    df["DatabaseHaveWorkedWith"]
    .dropna()
    .str.split(";")
    .explode()
    .value_counts()
)

platforms_have_worked_counts = (
    df["PlatformHaveWorkedWith"]
        .dropna()
        .str.split(";")
        .explode()
        .value_counts()
)

webframeworks_have_worked_counts = (
    df["WebframeHaveWorkedWith"]
        .dropna()
        .str.split(";")
        .explode()
        .value_counts()
)

# Split WebframeHaveWorkedWith and create one row per platform
webframeworks_have_worked_df = (
    df[["ResponseId", "WebframeHaveWorkedWith"]]
    .dropna(subset=["WebframeHaveWorkedWith"])
    .assign(WebframeHaveWorkedWith=lambda x: x["WebframeHaveWorkedWith"].str.split(";"))
    .explode("WebframeHaveWorkedWith")
)

# Reset index
webframeworks_have_worked_df = webframeworks_have_worked_df.reset_index(drop=True)
webframeworks_have_worked_df.insert(0, "Id", range(1, len(webframeworks_have_worked_df) + 1))

# Find the top 10 web frameworks
top_10_web_frameworks = (
    webframeworks_have_worked_df["WebframeHaveWorkedWith"]
    .value_counts()
    .head(10)
)

# Keep only records belonging to the top 10 platforms
top_10_web_frameworks_df = webframeworks_have_worked_df[
    webframeworks_have_worked_df["WebframeHaveWorkedWith"].isin(top_10_web_frameworks.index)
]

languages_want_work_with_counts = (
    df["LanguageWantToWorkWith"]
        .dropna()
        .str.split(";")
        .explode()
        .value_counts()
)

databases_want_work_wth_counts = (
    df["DatabaseWantToWorkWith"]
    .dropna()
    .str.split(";")
    .explode()
    .value_counts()
)

platforms_want_work_with_counts = (
    df["PlatformWantToWorkWith"]
    .dropna()
    .str.split(";")
    .explode()
    .value_counts()
)

# Split WebframeWantToWorkWith and create one row per platform
webframeworks_want_work_with_df = (
    df[["ResponseId", "WebframeWantToWorkWith"]]
    .dropna(subset=["WebframeWantToWorkWith"])
    .assign(WebframeWantToWorkWith=lambda x: x["WebframeWantToWorkWith"].str.split(";"))
    .explode("WebframeWantToWorkWith")
)

# Reset index
webframeworks_want_work_with_df = webframeworks_want_work_with_df.reset_index(drop=True)
webframeworks_want_work_with_df.insert(0, "Id", range(1, len(webframeworks_want_work_with_df) + 1))

# Find the top 10 web frameworks want to work
top_10_web_frameworks_want_work_with = (
    webframeworks_want_work_with_df["WebframeWantToWorkWith"]
    .value_counts()
    .head(10)
)

# Keep only records belonging to the top 10 web frameworks respondents want to work with
top_10_web_frameworks_want_work_with_df = webframeworks_want_work_with_df[
    webframeworks_want_work_with_df["WebframeWantToWorkWith"].isin(top_10_web_frameworks_want_work_with.index)
]

top_10_web_frameworks_want_work_with_df.head(20)

    Id  ResponseId WebframeWantToWorkWith
0    1           2                Express
2    3           2                Node.js
3    4           2                  React
5    6           3           ASP.NET CORE
6    7          10                Express
7    8          10                Next.js
8    9          10                Node.js
9   10          10                  React
11  12          11                Node.js
12  13          11                  React
15  16          12           ASP.NET CORE
16  17          12                Express
18  19          12                Node.js
19  20          12                  React
20  21          19           ASP.NET CORE
22  23          23           ASP.NET CORE
26  27          27                Node.js
27  28          29                Angular
30  31          29           ASP.NET CORE
32  33          29                Next.js

In [23]:
# And save in a new file for our analysis
language_have_worked_counts.to_csv("survey-data-languages-have-worked-with.csv")
databases_have_worked_counts.to_csv("survey-data-databases-have-worked-with.csv")
platforms_have_worked_counts.to_csv("survey-data-platforms-have-worked-with.csv")
top_10_web_frameworks_df.to_csv("survey-data-webframeworks-have-worked-with.csv", index=False)
languages_want_work_with_counts.to_csv("survey-data-languages-want-work-with.csv")
databases_want_work_wth_counts.to_csv("survey-data-databases-want-work-with.csv")
platforms_want_work_with_counts.to_csv("survey-data-platforms-want-work-with.csv")
top_10_web_frameworks_want_work_with_df.to_csv("survey-data-webframeworks-want-work-with.csv", index=False)

In [ ]:
# Let's check the top 10 languages respondents have worked with
language_have_worked_counts.head(10)

LanguageHaveWorkedWith
JavaScript                 14943
SQL                        12602
HTML/CSS                   12410
TypeScript                 10709
Python                      9590
Bash/Shell (all shells)     7244
C#                          6340
Java                        5982
PHP                         4644
PowerShell                  3438
Name: count, dtype: int64

In [ ]:
# Let's check the top 10 databases respondents have worked with
databases_have_worked_counts.head(10)

DatabaseHaveWorkedWith
PostgreSQL              11514
MySQL                    8556
SQLite                   7021
MongoDB                  5930
Microsoft SQL Server     5870
Redis                    5814
MariaDB                  3994
Elasticsearch            3491
Dynamodb                 2268
Oracle                   1907
Name: count, dtype: int64

In [ ]:
# Let's check the top 10 platforms respondents have worked with
platforms_have_worked_counts.head(10)

PlatformHaveWorkedWith
Amazon Web Services (AWS)    10871
Microsoft Azure               6681
Google Cloud                  5537
Cloudflare                    3874
Digital Ocean                 3170
Firebase                      3025
Vercel                        2875
Heroku                        2002
Netlify                       1662
Hetzner                       1392
Name: count, dtype: int64

In [ ]:
# Let's check the top 10 web frameworks respondents have worked with
webframeworks_have_worked_counts.head(10)

WebframeHaveWorkedWith
Node.js         9230
React           8999
jQuery          4810
Express         4408
Next.js         4399
ASP.NET CORE    4319
Angular         4038
Vue.js          3642
ASP.NET         3094
Spring Boot     2916
Name: count, dtype: int64

In [ ]:
# Let's check the top 10 languages respondents want to work with
languages_want_work_with_counts.head(10)

LanguageWantToWorkWith
JavaScript                 11541
SQL                        10944
TypeScript                 10437
HTML/CSS                   10016
Python                      8919
Go                          5661
Rust                        5597
C#                          5590
Bash/Shell (all shells)     5582
Java                        4048
Name: count, dtype: int64